require 'csv'
cats= [
"Al D'Amato.HTML",
"Alan Cranston.HTML",
"Alan J. Dixon.HTML",
"Andrew Coats.HTML",
"Arlen Specter.HTML",
"Barry Goldwater.HTML",
"Bill Clark.HTML",
"Bill Gunter.HTML",
"Bill Schulz .HTML",
"Birch Baynh.HTML",
"Bob Dole.HTML",
"Bob Kasten.HTML",
"Bob Packwood.HTML",
"Bruce Green.HTML",
"Charles Mathias.HTML",
"Chris Dodd.HTML",
"Chuck Grassley.HTML",
"Clark Gruening .HTML",
"Cooper Brown.HTML",
"Dale Bumpers.HTML",
"Dan Berman.HTML",
"Dan Quayle.HTML",
"Daniel Inouye .HTML",
"Dave O'Neal.HTML",
"Don Nickles.HTML",
"Edward T. Conroy.HTML",
"Elizabeth Holtzman.HTML",
"Ernest Hollings.HTML",
"Frank Church.HTML",
"Frank Murkowski .HTML",
"Gary Hart.HTML",
"Gaylord Nelson.HTML",
"Gene McNary.HTML",
"George McGovern.HTML",
"Herman Talmadge.HTML",
"Jake Garn.HTML",
"James Abdnor.HTML",
"James E. Betts.HTML",
"James L. Buckley.HTML",
"Jeremiah Denton .HTML",
"Jim Folson Jr.HTML",
"Jim Griffin .HTML",
"John A. Durkin.HTML",
"John Culver.HTML",
"John Glenn.HTML",
"John P. East.HTML",
"John Simpson.HTML",
"Kent Johanneson.HTML",
"Mack Mattingly.HTML",
"Mark Andrews.HTML",
"Marshall T. Mays.HTML",
"Mary Buchanan.HTML",
"Mary Gojack.HTML",
"Patrick Leahy.HTML",
"Paul Gann.HTML",
"Paul Laxalt.HTML",
"Paula Hawkins.HTML",
"Pete Flaherty.HTML",
"Robert Burren Morgan.HTML",
"Russell B. Long.HTML",
"Slade Gorton.HTML",
"Steve Symms.HTML",
"Stewart M. Ledbetter.HTML",
"Ted Kulongoski.HTML",
"Thomas Eagleton.HTML",
"Warren G. Magnuson.HTML",
"Warren Rudman.HTML",
"Wendell H. Ford.HTML",
"Woody Jenkins.HTML",]
can_map = CSV.read(ARGV[0], headers:true, header_converters: :symbol, converters: :all).collect { |row| Hash[row.collect { |c,r| [c,r] }] }

cats.map {|c| c.gsub!(" ", "_")}
# puts cats

# cats.each do |c|
  name = "Jim Folson Jr.HTML".gsub(".HTML", "").split("_").map(&:strip)
  name.pop if name[-1] =~ /jr/i
  puts name
  puts can_map.select {|can| can[:candidatename].strip =~ /Jim[\s\n]+[a-z]?\.?[\s\n]*Folson/ && can[:yearelected] == 1980}
# end